[package]
name = "twm"
description = "A customizable workspace manager for tmux"
version = "0.9.0"
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/vinnymeller/twm"
include = ["src/**/*", "Cargo.toml", "LICENSE", "README.md"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = { version = "4.1", features = ["cargo", "derive"] }
config = "0.13"
serde = { version = "1", features = ["derive"] }
libc = "0.2"
indexmap = "1.9"
shellexpand = "3"
skim = "0.10"
walkdir = "2"
xdg = "2.4"
enum_dispatch = "0.3.13"
